// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/";
  };
  "./routes/mainLayout.tsx": {
    id: "routes/mainLayout";
    page: "/";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/mainLayout": typeof import("./app/./routes/mainLayout.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
};